# 🌈 Mad Libs Game - Fun Version by Hammad
import streamlit as st
import io

st.markdown("""
    <style>
        /* Yellow input focus border */
        input:focus {
            border: 2px solid #FFD700 !important;
            outline: none !important;
        }

        /* Book style output */
        .book-style {
            background: #fff9e6;
            padding: 30px;
            margin: 30px auto;
            border-radius: 12px;
            max-width: 700px;
            box-shadow: 4px 4px 20px rgba(0,0,0,0.1);
            font-family: 'Georgia', serif;
            line-height: 1.8;
            font-size: 18px;
            color: #333;
        }

        .book-style h2 {
            text-align: center;
            color: #DAA520;
            font-family: 'Cursive', sans-serif;
        }
    </style>
""", unsafe_allow_html=True)

st.markdown( """ <style> .tri-box { width: 240px; margin: auto; border: 3px solid yellow; border-radius: 20px; position: relative; padding: 10px; text-align: center; background-color: white; } .tri-box::after { content: ""; position: absolute; bottom: -35px; left: 50%; transform: translateX(-50%); width: 0; height: 0; border-left: 35px solid transparent; border-right: 35px solid transparent; border-top: 35px solid yellow; } </style> <div class='tri-box'> <img style='border-radius:15px;' src='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR4Ql7S-OkPm5DcoyqZNXOMshTERqvHNb6Vdg&s' width='200' /> <p><em>Your Story Time!</em></p> </div> """, unsafe_allow_html=True )
st.markdown("<h1 style='text-align:center; color:yellow;'>Mad Libs Story Generator! 👀</h1>", unsafe_allow_html=True)

input_dicts = {}
user_inputs = ["name", "favourite animal", "favourite food", "emotion", "adjective", "another adjective", "verb", "place"]

# Create columns
col1, col2 = st.columns(2)

for idx, input_name in enumerate(user_inputs):
    if idx % 2 == 0:
        with col1:
            input_dicts[input_name] = st.text_input(f"Enter your {input_name}:")
    else:
        with col2:
            input_dicts[input_name] = st.text_input(f"Enter your {input_name}:")

if st.button("Generate Story"):
    name = input_dicts.get("name")
    animal = input_dicts.get("favourite animal")
    food = input_dicts.get("favourite food")
    emotion = input_dicts.get("emotion")
    adjective1 = input_dicts.get("adjective")
    adjective2 = input_dicts.get("another adjective")
    verb = input_dicts.get("verb")
    place = input_dicts.get("place")

    story = f"""
    🌟 Once upon a time, there was a person named {name}.
    {name} had a pet {animal} who loved to eat {food} more than anything else in the world!

    One day, while feeling very {emotion}, they both decided to go on an adventure to the {place}.
    The weather was {adjective1} and the streets were {adjective2}.

    Suddenly, the {animal} started to {verb} right in front of everyone!
    People were surprised, but {name} just laughed and said,
    "By_By!" 😂

    And they lived happily ever after...

    ✨ THE END ✨
    """

    st.markdown("<div class='book-style'><h2>📖 Your Magical Story</h2><h2 style='font-size:10px'>App generated by hammad!</h2>" + story.replace("\n", "<br>") + "</div>", unsafe_allow_html=True)
    
    story_bytes = io.BytesIO()
    story_bytes.write(story.encode('utf-8'))  # Convert string to bytes
    story_bytes.seek(0)  # Rewind to start of the file

    st.download_button(
        label="📥 Download Your Story",  # Button ka text
        data=story_bytes,  # Story ko bytes me
        file_name="madlibs_story.txt",  # File name jo user ko download hogi
        mime="text/plain"  # MIME type, jo batata hai ke yeh text file hai
    )
